/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/signup": {
    /** 회원가입 (패스워드) */
    post: operations["AuthController_signup"];
  };
  "/api/v1/auth/login": {
    /** 로그인 (패스워드) */
    post: operations["AuthController_login"];
  };
  "/api/v1/auth/refresh": {
    /** Access 토큰 갱신 */
    post: operations["AuthController_refresh"];
  };
  "/api/v1/auth/logout": {
    /** 로그아웃 */
    post: operations["AuthController_logout"];
  };
  "/api/v1/auth/logout-all": {
    /** 모든 기기에서 로그아웃 */
    post: operations["AuthController_logoutAll"];
  };
  "/api/v1/auth/me": {
    /** 현재 사용자 정보 조회 */
    get: operations["AuthController_getProfile"];
  };
  "/api/v1/auth/sessions": {
    /** 활성 세션 목록 조회 */
    get: operations["AuthController_getSessions"];
  };
  "/api/v1/auth/local/signup": {
    /**
     * 플랫폼 자체 회원가입
     * @description 이메일과 비밀번호로 플랫폼에 직접 가입합니다. OAuth 계정이 이미 있는 경우 통합됩니다.
     */
    post: operations["LocalAuthController_signup"];
  };
  "/api/v1/auth/local/login": {
    /**
     * 플랫폼 자체 로그인
     * @description 이메일과 비밀번호로 로그인합니다. 성공 시 JWT 쿠키가 설정됩니다.
     */
    post: operations["LocalAuthController_login"];
  };
  "/api/v1/users": {
    /**
     * 사용자 목록 조회
     * @description 페이지네이션과 필터링을 지원하는 사용자 목록을 조회합니다.
     */
    get: operations["UsersController_findAll"];
    /**
     * 사용자 생성
     * @description 새로운 사용자를 생성합니다.
     */
    post: operations["UsersController_create"];
  };
  "/api/v1/users/{id}": {
    /**
     * 사용자 상세 조회
     * @description 특정 사용자의 상세 정보를 조회합니다.
     */
    get: operations["UsersController_findOne"];
    /**
     * 사용자 삭제
     * @description 특정 사용자를 삭제합니다.
     */
    delete: operations["UsersController_remove"];
    /**
     * 사용자 정보 수정
     * @description 특정 사용자의 정보를 수정합니다.
     */
    patch: operations["UsersController_update"];
  };
  "/api/v1/my": {
    /**
     * 마이페이지 메인 (리다이렉트)
     * @description 사용자의 역할에 따라 적절한 마이페이지로 리다이렉트합니다.
     */
    get: operations["MyPageController_redirectToRolePage"];
  };
  "/api/v1/my/influencer/overview": {
    /**
     * 인플루언서 마이페이지 개요
     * @description 프로필 요약, 지원 현황 카운트, 스크랩 수 등을 조회합니다.
     */
    get: operations["InfluencerMyPageController_getOverview"];
  };
  "/api/v1/my/influencer/resume": {
    /**
     * 인플루언서 이력서 조회
     * @description 자신의 이력서 정보를 조회합니다.
     */
    get: operations["InfluencerMyPageController_getResume"];
    /**
     * 인플루언서 이력서 수정
     * @description 자신의 이력서 정보를 수정합니다.
     */
    put: operations["InfluencerMyPageController_updateResume"];
  };
  "/api/v1/my/influencer/applications": {
    /**
     * 내 지원 현황 조회
     * @description 자신이 지원한 공고들의 현황을 조회합니다.
     */
    get: operations["InfluencerMyPageController_getMyApplications"];
  };
  "/api/v1/my/influencer/scraps": {
    /**
     * 내 스크랩 목록 조회
     * @description 자신이 스크랩한 공고들을 조회합니다.
     */
    get: operations["InfluencerMyPageController_getMyScraps"];
    /**
     * 공고 스크랩 생성
     * @description 관심 있는 공고를 스크랩합니다.
     */
    post: operations["InfluencerMyPageController_createScrap"];
  };
  "/api/v1/my/influencer/scraps/{jobPostId}": {
    /**
     * 스크랩 삭제
     * @description 스크랩한 공고를 제거합니다.
     */
    delete: operations["InfluencerMyPageController_deleteScrap"];
  };
  "/api/v1/my/advertiser/overview": {
    /**
     * 사업자 마이페이지 개요
     * @description 내가 작성한 공고 개수, 진행중/마감 카운트, 최근 지원자 수 등을 조회합니다.
     */
    get: operations["AdvertiserMyPageController_getOverview"];
  };
  "/api/v1/my/advertiser/job-posts": {
    /**
     * 내가 작성한 공고 목록 조회
     * @description 자신이 작성한 공고들을 조회합니다.
     */
    get: operations["AdvertiserMyPageController_getMyJobPosts"];
  };
  "/api/v1/my/advertiser/job-posts/{jobPostId}/applicants": {
    /**
     * 특정 공고의 지원자 목록 조회
     * @description 자신이 작성한 특정 공고에 지원한 인플루언서들을 조회합니다.
     */
    get: operations["AdvertiserMyPageController_getJobPostApplicants"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SignUpDto: {
      /**
       * @description 이메일 주소
       * @example user@example.com
       */
      email: string;
      /**
       * @description 사용자명
       * @example username123
       */
      username: string;
      /**
       * @description 표시 이름
       * @example 홍길동
       */
      displayName: string;
      /**
       * @description 비밀번호 (최소 8자, 영문/숫자/특수문자 포함)
       * @example SecurePass123!
       */
      password: string;
      /**
       * @description 사용자 역할
       * @example INFLUENCER
       * @enum {string}
       */
      role: "INFLUENCER" | "ADVERTISER" | "ADMIN";
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/avatar.jpg
       */
      avatar?: string;
      /**
       * @description 자기소개
       * @example 안녕하세요! 새로운 인플루언서입니다.
       */
      bio?: string;
      /**
       * @description 웹사이트 URL
       * @example https://example.com
       */
      website?: string;
    };
    AuthUserDto: {
      /**
       * @description 사용자 ID
       * @example clkv6r3ds0000qt6k5l7u8m1h
       */
      id: string;
      /**
       * @description 이메일
       * @example user@example.com
       */
      email: string;
      /**
       * @description 사용자명
       * @example username123
       */
      username: string;
      /**
       * @description 표시 이름
       * @example 홍길동
       */
      displayName: string;
      /**
       * @description 프로필 이미지
       * @example https://example.com/avatar.jpg
       */
      avatar?: string;
      /**
       * @description 사용자 역할
       * @example INFLUENCER
       * @enum {string}
       */
      role: "INFLUENCER" | "ADVERTISER" | "ADMIN";
      /**
       * @description 사용자 상태
       * @example ACTIVE
       * @enum {string}
       */
      status: "ACTIVE" | "INACTIVE" | "SUSPENDED";
      /**
       * @description 자기소개
       * @example 안녕하세요!
       */
      bio?: string;
      /**
       * @description 웹사이트 URL
       * @example https://example.com
       */
      website?: string;
      /**
       * Format: date-time
       * @description 계정 생성일
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description 마지막 수정일
       */
      updatedAt: string;
    };
    AuthResponseDto: {
      /** @description 사용자 정보 */
      user: components["schemas"]["AuthUserDto"];
      /**
       * @description Access 토큰 (15분 유효)
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      accessToken: string;
      /**
       * @description Refresh 토큰 (7일 유효)
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      refreshToken: string;
      /**
       * @description Access 토큰 만료 시간 (초)
       * @example 900
       */
      expiresIn: number;
    };
    LoginDto: {
      /**
       * @description 이메일 주소
       * @example user@example.com
       */
      email: string;
      /**
       * @description 비밀번호
       * @example SecurePass123!
       */
      password: string;
    };
    LocalSignupDto: {
      /**
       * @description 이메일 주소
       * @example user@example.com
       */
      email: string;
      /**
       * @description 비밀번호 (최소 6자, 최대 50자)
       * @example securePassword123
       */
      password: string;
      /**
       * @description 사용자 역할
       * @example INFLUENCER
       * @enum {string}
       */
      role: "INFLUENCER" | "ADVERTISER";
      /**
       * @description 표시 이름
       * @example 홍길동
       */
      displayName: string;
    };
    LocalLoginDto: {
      /**
       * @description 이메일 주소
       * @example user@example.com
       */
      email: string;
      /**
       * @description 비밀번호
       * @example securePassword123
       */
      password: string;
    };
    CreateUserDto: {
      /**
       * @description 이메일 주소
       * @example user@example.com
       */
      email: string;
      /**
       * @description 사용자명
       * @example username
       */
      username: string;
      /**
       * @description 표시 이름
       * @example 홍길동
       */
      displayName: string;
      /**
       * @description 비밀번호
       * @example password123
       */
      password: string;
      /**
       * @description 사용자 역할
       * @example user
       * @enum {string}
       */
      role: "INFLUENCER" | "ADVERTISER" | "ADMIN";
      /**
       * @description 사용자 상태
       * @example active
       * @enum {string}
       */
      status: "ACTIVE" | "INACTIVE" | "SUSPENDED";
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/avatar.jpg
       */
      avatar?: string;
      /**
       * @description 자기소개
       * @example 안녕하세요!
       */
      bio?: string;
      /**
       * @description 웹사이트 URL
       * @example https://example.com
       */
      website?: string;
    };
    UpdateUserDto: {
      /**
       * @description 사용자명
       * @example username
       */
      username?: string;
      /**
       * @description 표시 이름
       * @example 홍길동
       */
      displayName?: string;
      /**
       * @description 사용자 역할
       * @example user
       * @enum {string}
       */
      role?: "INFLUENCER" | "ADVERTISER" | "ADMIN";
      /**
       * @description 사용자 상태
       * @example active
       * @enum {string}
       */
      status?: "ACTIVE" | "INACTIVE" | "SUSPENDED";
      /**
       * @description 프로필 이미지 URL
       * @example https://example.com/avatar.jpg
       */
      avatar?: string;
      /**
       * @description 자기소개
       * @example 안녕하세요!
       */
      bio?: string;
      /**
       * @description 웹사이트 URL
       * @example https://example.com
       */
      website?: string;
    };
    UpdateInfluencerResumeDto: {
      /**
       * @description 한 줄 소개
       * @example 테크 리뷰 전문 인플루언서입니다.
       */
      headline?: string;
      /**
       * @description 자기소개
       * @example 안녕하세요! 5년간 테크 리뷰를 해온 인플루언서입니다...
       */
      bio?: string;
      /**
       * @description 보유 기술/관심 키워드
       * @example [
       *   "스마트폰",
       *   "노트북",
       *   "가전제품",
       *   "IT 트렌드"
       * ]
       */
      skills?: string[];
      /**
       * @description 포트폴리오 링크
       * @example [
       *   "https://youtube.com/c/mytech",
       *   "https://instagram.com/mytech"
       * ]
       */
      portfolioUrls?: string[];
      /**
       * @description 자유 양식 이력서 (JSON 형태)
       * @example {
       *   "education": [
       *     {
       *       "school": "서울대학교",
       *       "major": "컴퓨터과학과",
       *       "degree": "학사",
       *       "year": "2020"
       *     }
       *   ],
       *   "career": [
       *     {
       *       "company": "ABC회사",
       *       "position": "마케터",
       *       "period": "2020-2022"
       *     }
       *   ],
       *   "certifications": [
       *     {
       *       "name": "정보처리기사",
       *       "issuer": "한국산업인력공단",
       *       "year": "2020"
       *     }
       *   ]
       * }
       */
      resumeJson?: Record<string, never>;
    };
    CreateScrapDto: {
      /**
       * @description 스크랩할 공고 ID
       * @example clxxxxx
       */
      jobPostId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** 회원가입 (패스워드) */
  AuthController_signup: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpDto"];
      };
    };
    responses: {
      /** @description 회원가입 성공 */
      201: {
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
      /** @description 잘못된 요청 데이터 */
      400: {
        content: never;
      };
    };
  };
  /** 로그인 (패스워드) */
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      /** @description 로그인 성공 */
      200: {
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
      /** @description 인증 실패 */
      401: {
        content: never;
      };
    };
  };
  /** Access 토큰 갱신 */
  AuthController_refresh: {
    responses: {
      /** @description 토큰 갱신 성공 */
      200: {
        content: never;
      };
      /** @description 유효하지 않은 Refresh 토큰 */
      401: {
        content: never;
      };
    };
  };
  /** 로그아웃 */
  AuthController_logout: {
    responses: {
      /** @description 로그아웃 성공 */
      200: {
        content: never;
      };
    };
  };
  /** 모든 기기에서 로그아웃 */
  AuthController_logoutAll: {
    responses: {
      /** @description 전체 로그아웃 성공 */
      200: {
        content: never;
      };
    };
  };
  /** 현재 사용자 정보 조회 */
  AuthController_getProfile: {
    responses: {
      /** @description 사용자 정보 조회 성공 */
      200: {
        content: never;
      };
    };
  };
  /** 활성 세션 목록 조회 */
  AuthController_getSessions: {
    responses: {
      /** @description 세션 목록 조회 성공 */
      200: {
        content: never;
      };
    };
  };
  /**
   * 플랫폼 자체 회원가입
   * @description 이메일과 비밀번호로 플랫폼에 직접 가입합니다. OAuth 계정이 이미 있는 경우 통합됩니다.
   */
  LocalAuthController_signup: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocalSignupDto"];
      };
    };
    responses: {
      /** @description 회원가입 성공. JWT 쿠키가 설정됩니다. */
      201: {
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            /** @example 회원가입이 완료되었습니다. */
            message?: string;
            user?: {
              id?: string;
              email?: string;
              displayName?: string;
              role?: string;
            };
          };
        };
      };
      /** @description 이미 가입된 이메일 */
      409: {
        content: {
          "application/json": {
            /** @example false */
            success?: boolean;
            /** @example 이미 가입된 이메일입니다. */
            message?: string;
          };
        };
      };
      /** @description Rate limit exceeded */
      429: {
        content: {
          "application/json": {
            /** @example false */
            success?: boolean;
            /** @example 너무 많은 요청입니다. 잠시 후 다시 시도해주세요. */
            message?: string;
          };
        };
      };
    };
  };
  /**
   * 플랫폼 자체 로그인
   * @description 이메일과 비밀번호로 로그인합니다. 성공 시 JWT 쿠키가 설정됩니다.
   */
  LocalAuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocalLoginDto"];
      };
    };
    responses: {
      /** @description 로그인 성공. JWT 쿠키가 설정됩니다. */
      200: {
        content: {
          "application/json": {
            /** @example true */
            success?: boolean;
            /** @example 로그인되었습니다. */
            message?: string;
            user?: {
              id?: string;
              email?: string;
              displayName?: string;
              role?: string;
              avatar?: string | null;
            };
          };
        };
      };
      /** @description 인증 실패 */
      401: {
        content: {
          "application/json": {
            /** @example false */
            success?: boolean;
            /** @example 이메일 또는 비밀번호가 올바르지 않습니다. */
            message?: string;
          };
        };
      };
      /** @description Rate limit exceeded */
      429: {
        content: {
          "application/json": {
            /** @example false */
            success?: boolean;
            /** @example 너무 많은 요청입니다. 잠시 후 다시 시도해주세요. */
            message?: string;
          };
        };
      };
    };
  };
  /**
   * 사용자 목록 조회
   * @description 페이지네이션과 필터링을 지원하는 사용자 목록을 조회합니다.
   */
  UsersController_findAll: {
    parameters: {
      query?: {
        /** @description 페이지 번호 */
        page?: number;
        /** @description 페이지당 항목 수 */
        limit?: number;
        /** @description 사용자 역할로 필터링 */
        role?: "INFLUENCER" | "ADVERTISER" | "ADMIN";
        /** @description 사용자 상태로 필터링 */
        status?: "ACTIVE" | "INACTIVE" | "SUSPENDED";
        /** @description 검색 키워드 (사용자명, 표시 이름, 이메일) */
        search?: string;
      };
    };
    responses: {
      /** @description 사용자 목록이 성공적으로 조회되었습니다. */
      200: {
        content: never;
      };
    };
  };
  /**
   * 사용자 생성
   * @description 새로운 사용자를 생성합니다.
   */
  UsersController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description 사용자가 성공적으로 생성되었습니다. */
      201: {
        content: never;
      };
      /** @description 잘못된 요청 데이터입니다. */
      400: {
        content: never;
      };
      /** @description 이미 존재하는 사용자입니다. */
      409: {
        content: never;
      };
    };
  };
  /**
   * 사용자 상세 조회
   * @description 특정 사용자의 상세 정보를 조회합니다.
   */
  UsersController_findOne: {
    parameters: {
      path: {
        /** @description 사용자 UUID */
        id: string;
      };
    };
    responses: {
      /** @description 사용자 정보가 성공적으로 조회되었습니다. */
      200: {
        content: never;
      };
      /** @description 사용자를 찾을 수 없습니다. */
      404: {
        content: never;
      };
    };
  };
  /**
   * 사용자 삭제
   * @description 특정 사용자를 삭제합니다.
   */
  UsersController_remove: {
    parameters: {
      path: {
        /** @description 사용자 UUID */
        id: string;
      };
    };
    responses: {
      /** @description 사용자가 성공적으로 삭제되었습니다. */
      204: {
        content: never;
      };
      /** @description 사용자를 찾을 수 없습니다. */
      404: {
        content: never;
      };
    };
  };
  /**
   * 사용자 정보 수정
   * @description 특정 사용자의 정보를 수정합니다.
   */
  UsersController_update: {
    parameters: {
      path: {
        /** @description 사용자 UUID */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
    responses: {
      /** @description 사용자 정보가 성공적으로 수정되었습니다. */
      200: {
        content: never;
      };
      /** @description 잘못된 요청 데이터입니다. */
      400: {
        content: never;
      };
      /** @description 사용자를 찾을 수 없습니다. */
      404: {
        content: never;
      };
    };
  };
  /**
   * 마이페이지 메인 (리다이렉트)
   * @description 사용자의 역할에 따라 적절한 마이페이지로 리다이렉트합니다.
   */
  MyPageController_redirectToRolePage: {
    responses: {
      /** @description 역할별 마이페이지로 리다이렉트 */
      302: {
        headers: {
          /** @description 리다이렉트될 URL (/my/influencer 또는 /my/advertiser) */
          Location?: string;
        };
        content: never;
      };
    };
  };
  /**
   * 인플루언서 마이페이지 개요
   * @description 프로필 요약, 지원 현황 카운트, 스크랩 수 등을 조회합니다.
   */
  InfluencerMyPageController_getOverview: {
    responses: {
      /** @description 개요 정보 조회 성공 */
      200: {
        content: {
          "application/json": {
            profile?: {
              headline?: string | null;
              totalFollowers?: number;
              avgEngagement?: number;
              ratePerPost?: number | null;
              channelCount?: number;
            };
            applications?: {
              total?: number;
              pending?: number;
              accepted?: number;
              rejected?: number;
              withdrawn?: number;
            };
            scrapCount?: number;
            stats?: {
              completedContracts?: number;
              avgRating?: number;
            };
          };
        };
      };
    };
  };
  /**
   * 인플루언서 이력서 조회
   * @description 자신의 이력서 정보를 조회합니다.
   */
  InfluencerMyPageController_getResume: {
    responses: {
      /** @description 이력서 정보 조회 성공 */
      200: {
        content: never;
      };
    };
  };
  /**
   * 인플루언서 이력서 수정
   * @description 자신의 이력서 정보를 수정합니다.
   */
  InfluencerMyPageController_updateResume: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateInfluencerResumeDto"];
      };
    };
    responses: {
      /** @description 이력서 수정 성공 */
      200: {
        content: never;
      };
    };
  };
  /**
   * 내 지원 현황 조회
   * @description 자신이 지원한 공고들의 현황을 조회합니다.
   */
  InfluencerMyPageController_getMyApplications: {
    parameters: {
      query?: {
        /** @description 페이지네이션 커서 */
        cursor?: string;
        /** @description 한 페이지 항목 수 (기본: 20, 최대: 100) */
        limit?: number;
        /** @description 지원서 상태 필터 */
        status?: "PENDING" | "ACCEPTED" | "REJECTED" | "WITHDRAWN";
      };
    };
    responses: {
      /** @description 지원 현황 조회 성공 */
      200: {
        content: never;
      };
    };
  };
  /**
   * 내 스크랩 목록 조회
   * @description 자신이 스크랩한 공고들을 조회합니다.
   */
  InfluencerMyPageController_getMyScraps: {
    parameters: {
      query?: {
        /** @description 페이지네이션 커서 */
        cursor?: string;
        /** @description 한 페이지 항목 수 (기본: 20, 최대: 100) */
        limit?: number;
      };
    };
    responses: {
      /** @description 스크랩 목록 조회 성공 */
      200: {
        content: never;
      };
    };
  };
  /**
   * 공고 스크랩 생성
   * @description 관심 있는 공고를 스크랩합니다.
   */
  InfluencerMyPageController_createScrap: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateScrapDto"];
      };
    };
    responses: {
      /** @description 스크랩 생성 성공 */
      201: {
        content: never;
      };
      /** @description 이미 스크랩한 공고 */
      409: {
        content: never;
      };
    };
  };
  /**
   * 스크랩 삭제
   * @description 스크랩한 공고를 제거합니다.
   */
  InfluencerMyPageController_deleteScrap: {
    parameters: {
      path: {
        /** @description 공고 ID */
        jobPostId: string;
      };
    };
    responses: {
      /** @description 스크랩 삭제 성공 */
      200: {
        content: never;
      };
      /** @description 스크랩을 찾을 수 없음 */
      404: {
        content: never;
      };
    };
  };
  /**
   * 사업자 마이페이지 개요
   * @description 내가 작성한 공고 개수, 진행중/마감 카운트, 최근 지원자 수 등을 조회합니다.
   */
  AdvertiserMyPageController_getOverview: {
    responses: {
      /** @description 개요 정보 조회 성공 */
      200: {
        content: {
          "application/json": {
            company?: {
              name?: string;
              industry?: string;
              description?: string | null;
            };
            jobPosts?: {
              total?: number;
              open?: number;
              closed?: number;
              completed?: number;
              cancelled?: number;
            };
            recentStats?: {
              recentApplications?: number;
              activeContracts?: number;
              avgRating?: number;
            };
          };
        };
      };
    };
  };
  /**
   * 내가 작성한 공고 목록 조회
   * @description 자신이 작성한 공고들을 조회합니다.
   */
  AdvertiserMyPageController_getMyJobPosts: {
    parameters: {
      query?: {
        /** @description 페이지네이션 커서 */
        cursor?: string;
        /** @description 한 페이지 항목 수 (기본: 20, 최대: 100) */
        limit?: number;
        /** @description 공고 상태 필터 */
        status?: "OPEN" | "CLOSED" | "COMPLETED" | "CANCELLED";
      };
    };
    responses: {
      /** @description 공고 목록 조회 성공 */
      200: {
        content: {
          "application/json": {
            items?: ({
                id?: string;
                title?: string;
                description?: string;
                budget?: number | null;
                categories?: string[];
                platforms?: string[];
                /** Format: date-time */
                deadline?: string | null;
                status?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
                stats?: {
                  applicationCount?: number;
                  offerCount?: number;
                };
                recentApplicants?: ({
                    id?: string;
                    user?: {
                      displayName?: string;
                      avatar?: string | null;
                    };
                  })[];
              })[];
            hasMore?: boolean;
            nextCursor?: string | null;
          };
        };
      };
    };
  };
  /**
   * 특정 공고의 지원자 목록 조회
   * @description 자신이 작성한 특정 공고에 지원한 인플루언서들을 조회합니다.
   */
  AdvertiserMyPageController_getJobPostApplicants: {
    parameters: {
      query?: {
        /** @description 페이지네이션 커서 */
        cursor?: string;
        /** @description 한 페이지 항목 수 (기본: 20, 최대: 100) */
        limit?: number;
        /** @description 지원서 상태 필터 */
        status?: "PENDING" | "ACCEPTED" | "REJECTED" | "WITHDRAWN";
      };
      path: {
        /** @description 공고 ID */
        jobPostId: string;
      };
    };
    responses: {
      /** @description 지원자 목록 조회 성공 */
      200: {
        content: {
          "application/json": {
            jobPost?: {
              id?: string;
              title?: string;
            };
            items?: ({
                id?: string;
                status?: string;
                coverLetter?: string | null;
                proposedRate?: number | null;
                /** Format: date-time */
                appliedAt?: string;
                influencer?: {
                  id?: string;
                  displayName?: string;
                  avatar?: string | null;
                  profile?: ({
                    headline?: string | null;
                    followers?: number;
                    avgEngagement?: number;
                    categories?: string[];
                    ratePerPost?: number | null;
                    channelCount?: number;
                    topChannels?: {
                        platform?: string;
                        followers?: number;
                        url?: string;
                      }[];
                  }) | null;
                };
              })[];
            hasMore?: boolean;
            nextCursor?: string | null;
          };
        };
      };
      /** @description 해당 공고에 대한 권한이 없음 */
      403: {
        content: never;
      };
      /** @description 존재하지 않는 공고 */
      404: {
        content: never;
      };
    };
  };
}
